app/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from authentication.views import ProfileView, SceneIDAuthRedirect, SceneIDAuthReturn, set_profile_share

app_name = "authentication"

urlpatterns = [
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/set-share/', set_profile_share, name="set-profile-share"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('sceneid/auth/', SceneIDAuthRedirect.as_view(), name="auth"),
    path('sceneid/login/', SceneIDAuthReturn.as_view(), name="sceneid_return")
]

app/config/urls.py
import sys
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from rest_framework import routers

from authentication.api.v1.views import MeView
from party.api.v1.routers import router as v1_party_router
from authentication.api.v1.routers import router as v1_authentication_router
from party.views.feeds import FeedsView
from common.feeds import PartyFeedRss2, PartyFeedRss09, PartyFeedAtom1

v1router = routers.DefaultRouter() if settings.DEBUG else routers.SimpleRouter()

v1router.registry.extend(v1_party_router.registry)
if settings.DEBUG:
    v1router.registry.extend(v1_authentication_router.registry)

urlpatterns = [
    path('autocomplete/', include('autocomplete_contrib.urls')),
    path('admin/', admin.site.urls),
    path('feeds/', FeedsView.as_view(), name="feeds"),
    path('feeds/parties_rss2.xml', PartyFeedRss2(), name="feeds-rss2"),
    path('feeds/parties_rss09.xml', PartyFeedRss09(), name="feeds-rss09"),
    path('feeds/parties_atom1.xml', PartyFeedAtom1(), name="feeds-atom1"),
    path('api/v1/', include(v1router.urls)),
    path('api/v1/me/', MeView.as_view(), name='me'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('logviewer/', include('logviewer.urls')),
    path('account/', include('authentication.urls')),
    path('', include('party.urls')),
]

if settings.DEBUG and "test" not in sys.argv:
    import debug_toolbar

    # This will enable static assets even when debugging using gunicorn etc
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

app/party/urls.py
from django.urls import path

from party.views.site import LandingPageView, AboutView, SearchView, StatsView, ShareView, health_check
from party.views.party import PartyListView, PartyCreateView, PartyDetailView, PartyUpdateView, DemopartyNetCreateView
from party.views.trip import TripToCreateView, TripFromCreateView, TripToUpdateView, TripFromUpdateView, \
    TripToCloneView, TripFromCloneView, TripDeleteView

app_name = "party"

urlpatterns = [
    path('', LandingPageView.as_view(), name="landing_page"),
    path('about/', AboutView.as_view(), name="about"),
    path('search/', SearchView.as_view(), name="search"),
    path('stats/', StatsView.as_view(), name="stats"),
    path('health-check/', health_check, name="health-check"),
    path('shared/<str:short_uuid>/', ShareView.as_view(), name="shared"),
    path('list/', PartyListView.as_view(), name="list"),
    path('list/<int:year>/', PartyListView.as_view(), name="list-by-year"),
    path('list/<str:country>/', PartyListView.as_view(), name="list-by-country"),
    path('list/<str:country>/<int:year>/', PartyListView.as_view(), name="list-by-country-and-year"),
    path('create/', PartyCreateView.as_view(), name="create"),
    path('create/demopartynet/', DemopartyNetCreateView.as_view(), name="demopartynet-create"),
    path('<slug:slug>/update/', PartyUpdateView.as_view(), name="update"),
    path('create-trip-to/<slug:slug>/', TripToCreateView.as_view(), name="create-trip-to"),
    path('create-trip-from/<slug:slug>/', TripFromCreateView.as_view(), name="create-trip-from"),
    path('clone-trip-to/<slug:slug>/from_trip/<int:trip>/', TripToCloneView.as_view(), name="clone-trip-to"),
    path('clone-trip-from/<slug:slug>/from_trip/<int:trip>/', TripFromCloneView.as_view(), name="clone-trip-from"),
    path('update-trip-to/<slug:slug>/<int:trip>/', TripToUpdateView.as_view(), name="update-trip-to"),
    path('update-trip-from/<slug:slug>/<int:trip>/', TripFromUpdateView.as_view(), name="update-trip-from"),
    path('<slug:slug>/delete-trip/<int:pk>/', TripDeleteView.as_view(), name="delete-trip"),
    path('<slug:slug>/', PartyDetailView.as_view(), name="detail")
]

app/party/models.py
import re

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField
from django_extensions.db.fields import AutoSlugField
from django_extensions.db.models import TimeStampedModel

from common.parsers import strip_trailing_year
from party.managers import UpcomingPartyManager, PastPartyManager, PartyManager


class Party(models.Model):
    name = models.CharField(max_length=64)
    date_start = models.DateField()
    date_end = models.DateField()
    location = models.CharField(max_length=128)
    country = CountryField(multiple=False, null=True, blank=True)
    www = models.URLField(blank=True, null=True)
    slug = AutoSlugField(populate_from=["name", "date_start__year"])

    created_dt = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Created datetime')
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name="created_parties")
    modified_dt = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Modified datetime')
    modified_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, blank=True, null=True,
                                    related_name="modified_parties")

    visible = models.BooleanField(default=True)

    objects = PartyManager()
    upcoming_parties = UpcomingPartyManager()
    past_parties = PastPartyManager()

    def __str__(self):
        return f"{self.name} ({self.date_start.year})"

    def save(self, *args, **kwargs):
        if self.name.endswith(str(self.date_start.year)):
            self.name = strip_trailing_year(self.name)
        super().save(*args, **kwargs)

    @property
    def has_ended(self):
        return self.date_end < timezone.localtime().date()

    @property
    def date_range(self):
        """
        Let's jump through some hoops to format a nice date range
        """
        if self.date_start == self.date_end:
            # One day parties
            return self.date_start.strftime('%b %e, %Y')

        date_start = self.date_start.strftime('%b %e %Y')
        date_end = self.date_end.strftime('%b %e %Y')
        range_str = '%s - %s' % (date_start, date_end)
        r = re.findall(r'\d\d\d\d', range_str)
        if r and len(set(r)) == 1:
            # If years match, remove the first one
            range_str = re.sub(r'\d\d\d\d', '', range_str, count=1)
        words = range_str.split()
        # Remove recurring months
        range_str = ' '.join(sorted(set(words), key=words.index))
        # Clear multiple whitespaces, add comma before year
        range_str = re.sub(r'\s+', r' ', range_str).strip()
        return re.sub(r'(\s\d\d\d\d)', r',\1', range_str)


class Trip(TimeStampedModel):
    BICYCLE = 'bicycle'
    BUS = 'bus'
    CAR = 'car'
    MOTORCYCLE = 'motorcycle'
    PLANE = 'plane'
    SHIP = 'ship'
    TRAIN = 'train'
    WALKING = 'walking'
    OTHER = 'other'

    TYPES = [
        (BICYCLE, 'Bicycle'),
        (SHIP, 'Boat'),
        (BUS, 'Bus'),
        (CAR, 'Car'),
        (MOTORCYCLE, 'Motorcycle'),
        (PLANE, 'Plane'),
        (TRAIN, 'Train'),
        (WALKING, 'Walking'),
        (OTHER, 'Other')
    ]

    party = models.ForeignKey(Party, on_delete=models.CASCADE, related_name="trips")
    display_name = models.CharField(max_length=255)
    type = models.CharField(max_length=13, choices=TYPES, default=PLANE)
    departure_town = models.CharField(max_length=64)
    departure_country = CountryField(blank=True)
    departure_datetime = models.DateTimeField()
    arrival_town = models.CharField(max_length=64)
    arrival_country = CountryField(blank=True)
    arrival_datetime = models.DateTimeField()
    detail1 = models.CharField(max_length=32, blank=True, null=True)
    detail2 = models.CharField(max_length=32, blank=True, null=True)
    towards_party = models.BooleanField(default=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name="trips", blank=True,
                                   null=True)

    def __str__(self):
        return f'{self.display_name} ({self.departure_town} -> {self.arrival_town})'

app/party/views/feeds.py
from django.views.generic import TemplateView


class FeedsView(TemplateView):
    template_name = 'party/feeds.html'

app/party/views/party.py
import string

import requests
from django.db.models.functions import Lower
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.text import slugify
from django.views import generic
from django_countries import countries

from common.mixins import LoginRequiredMixin
from party.forms import PartyForm, PartyFormNative
from party.models import Party
from party.parsers import get_country, get_location, get_start_date, get_end_date


class PartyListView(generic.ListView):
    template_name = 'party/party_list.html'
    model = Party

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ret_arr = []
        for i in ["country", "year"]:
            if self.kwargs.get(i):
                ret_arr.append(string.capwords(str(self.kwargs.get(i))))
        ctx["breadcrumb"] = ret_arr
        ctx["party_years"] = list(Party.objects.filter(visible=True).values_list("date_start__year", flat=True).order_by("date_start__year").distinct())
        party_countries = [countries.name(x.get("country")) for x in Party.objects.filter(visible=True).values("country").distinct()]
        ctx["party_countries"] = sorted(party_countries)
        return ctx

    def get_queryset(self):
        qs = Party.objects.filter(visible=True).order_by(Lower("name"), "date_start")
        if "year" in self.kwargs:
            qs = qs.filter(date_start__year=self.kwargs.get("year"))
        if "country" in self.kwargs:
            qs = qs.filter(country__icontains=self.kwargs.get("country"))
        return qs


class PartyCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'party/party_create.html'
    model = Party
    queryset = Party.objects.filter(visible=True)

    def get_form_class(self):
        if self.request.user_agent.is_mobile:
            return PartyFormNative
        return PartyForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.visible = True
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("party:landing_page")


class PartyUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'party/party_create.html'
    model = Party
    form_class = PartyForm

    def get(self, request, *args, **kwargs):
        party = self.get_object()
        if party.has_ended:
            messages.warning(request, "Cannot modify a party that has ended")
            return redirect(reverse("party:landing_page"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        form.instance.visible = self.get_object().visible
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("party:detail", kwargs=self.kwargs)


class PartyDetailView(generic.DetailView):
    template_name = 'party/party_detail.html'
    model = Party

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        trips = self.object.trips.select_related("created_by").order_by(Lower("display_name"))
        ctx["inbound"] = trips.filter(towards_party=True)
        ctx["outbound"] = trips.filter(towards_party=False)
        return ctx


class DemopartyNetCreateView(LoginRequiredMixin, generic.RedirectView):
    def get(self, request, *args, **kwargs):
        demopartynet_url = request.GET.get("url", None)
        if not demopartynet_url:
            messages.warning(request, "No demoparty.net url provided")
            return redirect(reverse("party:landing_page"))

        res = requests.get(timeout=10, url=f"https://www.demoparty.net{demopartynet_url}.jsonld")
        if res.status_code != 200:
            messages.warning(request, "Error fetching data from demoparty.net")
            return redirect(reverse("party:landing_page"))

        j = res.json()

        defaults = {
            "created_by": request.user,
            "location": get_location(j),
            "country": get_country(j),
            "name": j.get("name"),
            "www": j.get("url"),
            "date_start": get_start_date(j),
            "date_end": get_end_date(j),
        }

        party, _ = Party.objects.update_or_create(slug=slugify(defaults["name"]), defaults=defaults)
        return redirect('party:detail', party.slug)

app/party/templates/party/create.html
{% extends 'party/base.html' %}{% load crispy_forms_tags %}

{% block title %}
    <title>Create a new party | Darklite Partywiki</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3>Add a party</h3>
                {% comment %}{% crispy form %}{% endcomment %}
                {% crispy form %}
                <p>Fields with (*) are mandatory</p>
            </div>
            {% if parties %}
                <div class="col-sm-6">
                    <h3>Or select from <a href="https://www.demoparty.net/">demoparty.net</a></h3>
                    {% for party in parties %}
                        <li><a href="{% url 'party:demopartynet-create' %}?slug={{ party.0|slugify }}">{{ party.0 }}</a>
                        </li>
                    {% endfor %}
                    <!-- https://www.demoparty.net/unique-event/hashembly-winter-2021.jsonld -->
                </div>
            {% endif %}
        </div>
    </div>

    {% comment %}    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/locale/en-gb.min.js"
            integrity="sha512-w+tDY4gx49+DNVlN7Nmc9ldOkh6nP3w4txBTEatSx3XrZdfYtX9+oylJjQ7RqeeDzDebG3u1VAg/gM5Td2Bd5Q=="
            crossorigin="anonymous"></script>{% endcomment %}

{% endblock %}

app/party/templates/party/landing_page.html
{% extends 'party/base.html' %}

{% block extrahead %}
    {% if request.user.is_authenticated %}
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const parties = localStorage.getItem("partyList") ? JSON.parse(localStorage.getItem("partyList")) : [],
                    partyList = []
                document.querySelectorAll("tbody tr").forEach(row => {
                    const id = Number(row.dataset.partyId),
                        partyGoers = Number(row.dataset.partyGoers),
                        party = parties.find(party => party.id === id)
                    if (!party || partyGoers > party.partyGoers) {
                        row.querySelector("#marker").classList.remove("d-none")
                        document.querySelector("#marker-helptext").classList.remove("d-none")
                    }
                    if (!party) row.querySelector("#badge").classList.remove("d-none")
                    partyList.push({id, partyGoers})
                })
                localStorage.setItem("partyList", JSON.stringify(partyList))
            })
        </script>
        <style>
            #badge {
                scale: 0.8;
            }
        </style>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container py-1">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-8">
                        <h1 class="">Upcoming parties</h1>
                    </div>
                    <div class="col-md-4 text-right mb-3">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'party:create' %}" class="btn btn-primary">
                                <i class="fa fa-plus me-2" aria-hidden="true"></i>ADD PARTY</a>
                        {% else %}
                            <a href="{% url 'authentication:auth' %}" class="btn btn-primary">LOGIN TO ADD PARTY</a>
                        {% endif %}
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover w-auto mb-1">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Party</th>
                            <th class="text-center px-3">
                                <i class="fas fa-plane-arrival" title="To party"></i>
                            </th>
                            <th class="text-center">
                                <i class="fas fa-plane-departure" title="From party"></i>
                            </th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for party in upcoming_parties %}
                            <tr data-party-id="{{ party.id }}" data-party-goers="{{ party.towards_party_count }}">
                                <td>
                                    {% include 'snippets/flag.html' with country=party.country %}
                                </td>
                                <td>
                                    <a href="{% url 'party:detail' party.slug %}">
                                        {{ party }}
                                    </a>
                                </td>
                                <td class="text-center">
                                    {{ party.towards_party_count }}
                                    <sup id="marker" class="text-danger d-none">&bull;</sup>
                                </td>
                                <td class="text-center">
                                    {{ party.towards_home_count }}
                                </td>
                                <td>
                                    <span id="badge" class="badge rounded-pill text-bg-primary d-none">NEW</span>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <small id="marker-helptext" class="d-none">
                    <sup class="text-danger ms-2 me-1">&bull;</sup>New trips added</small>
            </div>
            <div class="col-md-4">
                <p class="lead bg-info text-center text-white">Recent parties</p>
                <ul class="list-unstyled bg-faded">
                    {% for party in past_parties|slice:"10" %}
                        <li>
                            {% include 'snippets/flag.html' with country=party.country %}
                            <a href="{% url 'party:detail' party.slug %}">
                                {{ party }} <small>{{ party.date_start__year }}</small>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>

{% endblock %}

app/party/templates/party/list.html
{% extends 'party/base.html' %}

{% block title %}
    <title>List of parties | Darklite Partywiki</title>
{% endblock %}

{% block content %}
    <div class="container">
        {% regroup object_list by name as parties %}
        <ul class="list-group">
            {% for party in parties %}
                <li class="list-group-item" style="padding: .35rem 1.25rem;">{{ party.grouper }}
                    {% for party_instance in party.list %}
                        <a href="{% url 'party:detail' party_instance.slug %}">{{ party_instance.date_start.year }}</a>
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'party:landing_page' %}">Home</a></li>
                        <li class="breadcrumb-item"><a
                                href="{% url 'party:list' %}">Parties</a></li>
                        {% comment %}                        <li class="breadcrumb-item"><a
                                href="{% url 'party:list' year %}">{{ year }}</a>
                        </li>{% endcomment %}
                        <li class="breadcrumb-item active">{{ object.name }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/party/templates/party/party_create.html
{% extends 'party/base.html' %}{% load crispy_forms_tags %}{% load countries %}

{% block title %}
    {% if request.resolver_match.view_name != "party:update" %}
        <title>Create a new party | Darklite Partywiki</title>
        <meta property="og:title" content="Create a new party | Darklite Partywiki"/>
    {% else %}
        <title>Modify a new party | Darklite Partywiki</title>
        <meta property="og:title" content="Modify a new party | Darklite Partywiki"/>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                {% if request.resolver_match.view_name != "party:update" %}
                    <h3>Add a party</h3>
                {% else %}
                    <h3>Modify a party</h3>
                {% endif %}
                {% crispy form %}
                <p>Fields with (*) are mandatory</p>
            </div>

            {% if request.resolver_match.view_name != "party:update" %}
                <div class="col-12 col-md-4">
                    <h3 class="mb-4">Or generate from <a href="https://www.demoparty.net/">demoparty.net</a></h3>
                    <div class="spinner-border float-right" role="status" id="demopartySpinner">
                        <span class="sr-only">Loading...</span>
                    </div>
                    <div style="list-style: none" id="partyList">
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="spinnerModal" data-backdrop="static" data-keyboard="false"
         tabindex="-1" aria-labelledby="spinnerModalLabel" aria-hidden="true">
        <div class="modal-dialog h-100 d-flex flex-column justify-content-center my-0">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="spinnerModalLabel">Just a moment...</h5>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-2 my-auto">
                            <div class="spinner-border float-right" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                        <div class="col my-auto">
                            Fetching data from demoparty.net
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <template id="listItem">
        <li>
            <div class="text-center" style="width: 20px; display: inline-block">
                <span class="fi" style="height: 12px;"></span>
            </div>
            <a class="createPartyLink ms-2"></a>
        </li>

    </template>

    <script type="text/javascript">
        $("#id_date_start").on("change.datetimepicker", e => {
            $("#id_date_end").val(e.target.value)
        })
    </script>

    {% if request.resolver_match.view_name != "party:update" %}
        <script>
            const partyList = document.getElementById("partyList"),
                spinner = document.getElementById("demopartySpinner"),
                date = new Date().toISOString().slice(0, 10)

            function getData() {
                fetch("https://www.demoparty.net/demoparties.xml")
                    .then(response => response.text())
                    .then(str => new window.DOMParser().parseFromString(str, "text/xml"))
                    .then(data => {
                        spinner.hidden = true
                        renderData(data)
                    })
            }

            function renderData(rssData) {
                let lastMonth
                const regionNames = 'Intl' in window ? new Intl.DisplayNames(['en'], {type: 'region'}) : false
                rssData.querySelectorAll("item").forEach(item => {
                    const countryName = regionNames ? regionNames.of(item.querySelector("country").textContent) : item.querySelector("country").textContent
                    const thisMonth = new Date(item.querySelector("startDate").textContent).toLocaleString('en-us', {month: 'long'})
                    if (lastMonth !== thisMonth) {
                        lastMonth = thisMonth
                        const header = document.createElement("h5")
                        header.className = "mt-2"
                        header.innerText = thisMonth
                        partyList.appendChild(header)
                    }
                    const content = document.getElementById("listItem").content.cloneNode(true)
                    const a = content.querySelector("a")
                    const span = content.querySelector("span")
                    span.classList.add("fi-" + item.querySelector("country").textContent.toLowerCase())
                    span.title = countryName
                    const url = new URL(item.querySelector("link").textContent)
                    a.href = "{% url 'party:demopartynet-create' %}?url=" + url.pathname
                    a.textContent = item.querySelector("title").textContent
                    a.addEventListener("click", () => {
                        $("#spinnerModal").modal("show")
                    })
                    partyList.append(content)
                })
            }

            getData()

        </script>
    {% endif %}

{% endblock %}

app/party/templates/party/trip_create.html
{% extends 'party/base.html' %}{% load crispy_forms_tags %}

{% block title %}
    <title>Create Trip | Darklite Partywiki</title>
    <meta property="og:title" content="Create Trip | Darklite Partywiki"/>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                {% if towards_party %}
                    <h3>Create a Trip to {{ party }}</h3>
                {% else %}
                    <h3>Create a Trip from {{ party }}</h3>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if not party_ended %}
                        <button class="btn btn-primary" type="submit">Save</button>
                        <a class="btn btn-primary ms-4" href="{% url 'party:detail' party.slug %}">Cancel</a>
                        {% if object %}
                            <a class="btn btn-danger ms-4"
                               href="{% url 'party:delete-trip' party.slug object.pk %}">Delete</a>
                        {% endif %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>

    <script>
        $("#id_departure_datetime").on("change.datetimepicker", e => {
            $("#id_arrival_datetime").val(e.target.value)
        })
    </script>

{% endblock %}

app/party/templates/party/trip_detail_row.html
<tr class="table-data-row">
    <td class="text-truncate handle-ellipsis"
        style="max-width: 150px" title="{{ trip.display_name }}">{{ trip.display_name }}
    </td>
    {% if not user.is_authenticated %}
        <td style="filter: blur(3px);">
            <i class="fas fa-sign-in-alt"></i>
            Login needed
        </td>
    {% else %}
        <td class="text-truncate handle-ellipsis" style="max-width: 150px">
            {% include 'snippets/flag.html' with country=trip.departure_country %}
            <span style="font-size: 0">{{ trip.departure_country.name }}</span>
            <span title="{{ trip.departure_town }}">{{ trip.departure_town }}</span>
        </td>
    {% endif %}

    {% if user.is_authenticated %}
        <td>{{ trip.departure_datetime|date:"D, d M Y H:i" }}</td>
    {% endif %}

    {% if not user.is_authenticated %}
        <td style="filter: blur(3px);">
            <i class="fas fa-sign-in-alt"></i>
            Login needed
        </td>
    {% else %}
        <td class="text-truncate handle-ellipsis" style="max-width: 150px">
            {% include 'snippets/flag.html' with country=trip.arrival_country %}
            <span style="font-size: 0">{{ trip.arrival_country.name }}</span>
            <span title="{{ trip.arrival_town }}">{{ trip.arrival_town }}</span>
        </td>
    {% endif %}
    {% if user.is_authenticated %}
        <td>{{ trip.arrival_datetime|date:"D, d M Y H:i" }}</td>
        <td>
            <i class="fa fa-{{ trip.type }} tripTypeIcon" title="{{ trip.type }}"></i>
            {% if trip.detail1 %}
                {{ trip.detail1 }}
            {% endif %}
        </td>
        <td>
            {% if trip.detail2 %}
                {{ trip.detail2 }}
            {% endif %}
        </td>

        {% if not object.has_ended %}
            <td class="text-right" nowrap="">
                {% if direction == "to" %}
                    <a href="{% url 'party:clone-trip-to' object.slug trip.pk %}" title="Clone this trip">
                        <i class="far fa-clone icon-help"></i></a>
                    {% if trip.created_by == user %}
                        <a class="ms-2"
                           href="{% url 'party:update-trip-to' object.slug trip.pk %}" title="Modify this trip">
                            <i class="far fa-edit icon-help"></i></a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'party:clone-trip-from' object.slug trip.pk %}" title="Clone this trip">
                        <i class="far fa-clone icon-help"></i></a>
                    {% if trip.created_by == user %}
                        <a class="ms-2"
                           href="{% url 'party:update-trip-from' object.slug trip.pk %}" title="Modify this trip">
                            <i class="far fa-edit icon-help"></i></a>
                    {% endif %}
                {% endif %}

            </td>
        {% endif %}

    {% endif %}
</tr>