app/config/urls.py
import sys
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from rest_framework import routers

from authentication.api.v1.views import MeView
from party.api.v1.routers import router as v1_party_router
from authentication.api.v1.routers import router as v1_authentication_router
from party.views.feeds import FeedsView
from common.feeds import PartyFeedRss2, PartyFeedRss09, PartyFeedAtom1

v1router = routers.DefaultRouter() if settings.DEBUG else routers.SimpleRouter()

v1router.registry.extend(v1_party_router.registry)
if settings.DEBUG:
    v1router.registry.extend(v1_authentication_router.registry)

urlpatterns = [
    path('autocomplete/', include('autocomplete_contrib.urls')),
    path('admin/', admin.site.urls),
    path('feeds/', FeedsView.as_view(), name="feeds"),
    path('feeds/parties_rss2.xml', PartyFeedRss2(), name="feeds-rss2"),
    path('feeds/parties_rss09.xml', PartyFeedRss09(), name="feeds-rss09"),
    path('feeds/parties_atom1.xml', PartyFeedAtom1(), name="feeds-atom1"),
    path('api/v1/', include(v1router.urls)),
    path('api/v1/me/', MeView.as_view(), name='me'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('logviewer/', include('logviewer.urls')),
    path('account/', include('authentication.urls')),
    path('', include('party.urls')),
]

if settings.DEBUG and "test" not in sys.argv:
    import debug_toolbar

    # This will enable static assets even when debugging using gunicorn etc
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

app/logviewer/urls.py
from django.urls import path

from logviewer.views import LogViewerIndexView, LogViewerDetailView

app_name = "logviewer"

urlpatterns = [
    path('', LogViewerIndexView.as_view(), name="index"),
    path('<str:filename>/', LogViewerDetailView.as_view(), name="detail")
]

app/party/urls.py
from django.urls import path

from party.views.site import LandingPageView, AboutView, SearchView, StatsView, ShareView, health_check
from party.views.party import PartyListView, PartyCreateView, PartyDetailView, PartyUpdateView, DemopartyNetCreateView
from party.views.trip import TripToCreateView, TripFromCreateView, TripToUpdateView, TripFromUpdateView, \
    TripToCloneView, TripFromCloneView, TripDeleteView

app_name = "party"

urlpatterns = [
    path('', LandingPageView.as_view(), name="landing_page"),
    path('about/', AboutView.as_view(), name="about"),
    path('search/', SearchView.as_view(), name="search"),
    path('stats/', StatsView.as_view(), name="stats"),
    path('health-check/', health_check, name="health-check"),
    path('shared/<str:short_uuid>/', ShareView.as_view(), name="shared"),
    path('list/', PartyListView.as_view(), name="list"),
    path('list/<int:year>/', PartyListView.as_view(), name="list-by-year"),
    path('list/<str:country>/', PartyListView.as_view(), name="list-by-country"),
    path('list/<str:country>/<int:year>/', PartyListView.as_view(), name="list-by-country-and-year"),
    path('create/', PartyCreateView.as_view(), name="create"),
    path('create/demopartynet/', DemopartyNetCreateView.as_view(), name="demopartynet-create"),
    path('<slug:slug>/update/', PartyUpdateView.as_view(), name="update"),
    path('create-trip-to/<slug:slug>/', TripToCreateView.as_view(), name="create-trip-to"),
    path('create-trip-from/<slug:slug>/', TripFromCreateView.as_view(), name="create-trip-from"),
    path('clone-trip-to/<slug:slug>/from_trip/<int:trip>/', TripToCloneView.as_view(), name="clone-trip-to"),
    path('clone-trip-from/<slug:slug>/from_trip/<int:trip>/', TripFromCloneView.as_view(), name="clone-trip-from"),
    path('update-trip-to/<slug:slug>/<int:trip>/', TripToUpdateView.as_view(), name="update-trip-to"),
    path('update-trip-from/<slug:slug>/<int:trip>/', TripFromUpdateView.as_view(), name="update-trip-from"),
    path('<slug:slug>/delete-trip/<int:pk>/', TripDeleteView.as_view(), name="delete-trip"),
    path('<slug:slug>/', PartyDetailView.as_view(), name="detail")
]

app/logviewer/models.py
from django.db import models

# Create your models here.

app/logviewer/views.py
import os
import re
import subprocess

from ipaddress import ip_address

from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import Http404, HttpResponse
from django.views import generic
from django.conf import settings


class AdminBaseView(UserPassesTestMixin, generic.TemplateView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True
        raise Http404


class LogViewerIndexView(AdminBaseView):
    template_name = 'logviewer/index.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        ctx["files"] = sorted(
            [(os.path.splitext(x)[0].capitalize(), os.stat(os.path.join("/var/log/", x)).st_size) for x in
             os.listdir("/var/log/") if x.endswith(".log")])
        return ctx


class LogViewerDetailView(AdminBaseView):
    template_name = "logviewer/detail.html"

    @staticmethod
    def _readlines_generator(filepath):
        with open(filepath) as raw_data:
            for line in raw_data:
                yield line

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        ctx["fail2ban"] = bool(settings.FAIL2BAN_JAILS)
        filepath = os.path.join("/var/log/", self.kwargs.get("filename").lower() + ".log")
        if not os.path.isfile(filepath):
            raise Http404

        regex = re.compile("^([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}) - - ")
        lines = ((''.join(regex.findall(x)), x) for x in self._readlines_generator(filepath))
        if self.request.GET.get("search"):
            lines = filter(lambda x: self.request.GET.get("search").lower() in x[1].lower(), lines)
        ctx["file_contents"] = lines
        return ctx

    def post(self, request, *args, **kwargs):
        ip = self.request.POST.get("ban_ip")

        if ip_address(ip.split("/")[0]).is_private:
            return HttpResponse(status=400, content=f"Invalid IP! {ip} belongs to a private IP group")
        command = [
            "echo",
            ip
        ]
        res = subprocess.run(command)
        print("RES", res)
        return HttpResponse(status=200, content=ip)

app/logviewer/templates/logviewer/detail.html
{% extends 'party/base.html' %}

{% block extrahead %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"
            integrity="sha512-ubuT8Z88WxezgSqf3RLuNi5lmjstiJcyezx34yIU2gAHonIi27Na7atqzUZCOoY4CExaoFumzOsFQ2Ch+I/HCw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block content %}

    <style>
        html, body {
            height: 95%;
        }

        table {
            font-size: 0.7em;
            font-family: monospace;
        }

        .hidden {
            display: none;
        }

        #filter {
            box-shadow: none;
        }
    </style>

    <body>
    <a id="top"></a>
    <a href="{% url 'logviewer:index' %}" class="ml-3">Back</a>
    &nbsp;&#124;&nbsp;
    <a href="#bottom">Go to bottom of page</a>

    <div class="container">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text"
                  id="inputGroup-sizing-default">Logfile&nbsp;&nbsp;<strong>{{ view.kwargs.filename }}</strong></span>
            </div>
            <input id="filter" type="text" class="form-control" placeholder="Filter..."/>
        </div>
    </div>
    <script>
        const regex = /([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})/
    </script>
    <form id="logForm">
        {% csrf_token %}
        <table class="table table-responsive table-sm table-striped table-hover ml-3">
            {% for row in file_contents %}
                <input type="hidden" name="logrow" value="logrow_{{ forloop.counter0 }}"/>
                <tr class="table-data-row">
                    <td>
                        {% if row.0 %}
                            {% include 'snippets/logviewer_context_menu.html' %}
                        {% endif %}
                    </td>
                    <td>{{ row.1 }}</td>
                </tr>
            {% endfor %}
        </table>
    </form>
    <a id="bottom"></a>
    <a href="#top">Go to top of page</a>

    <div class="modal fade" id="banModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="banModalLabel">Confirm IP ban</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="container mt-3 hidden" id="banAlert">
                    <div class="alert alert-danger" role="alert"></div>
                </div>
                <div class="modal-body" id="modal-body">
                    You are about to ban <span id="ban_ip">0.0.0.0</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" onclick="confirmBan()">
                        Confirm Ban
                    </button>
                </div>
            </div>
        </div>
    </div>


    <script>
        const input = document.querySelector('#filter');
        const items = document.getElementsByClassName('table-data-row')

        input.addEventListener('keyup', function (ev) {
            const text = ev.target.value;
            // Escape the search string
            // const pat = new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
            const pat = new RegExp(text, 'i');
            for (let i = 0; i < items.length; i++) {
                const item = items[i];
                if (pat.test(item.innerText)) {
                    item.classList.remove("hidden");
                } else {
                    item.classList.add("hidden");
                }
            }
        });

        const csrfmiddlewaretoken = document.querySelector("input[name=csrfmiddlewaretoken]").value
        const actionLinks = document.querySelectorAll(".dropdown-item")
        const banIP = document.querySelector("#ban_ip")
        const banAlert = document.querySelector("#banAlert")

        actionLinks.forEach((elem) => {
            elem.addEventListener("click", (e) => {
                console.log(e.target.dataset.command, e.target.dataset.value)
                if (e.target.dataset.command === "find") window.location = "?search=" + e.target.dataset.value
                if (e.target.dataset.command === "ban") {
                    banIP.innerText = e.target.dataset.value
                    $("#banModal").modal("show")
                }
            })
        })

        confirmBan = () => {
            console.log("Would ban " + banIP.innerText)
            $.post(window.location, {
                csrfmiddlewaretoken,
                ban_ip: banIP.innerText
            }).done((res) => {
                console.log(res)
            }).fail((res) => {
                console.log("ERROR ", res)
                banAlert.children[0].innerText = res.responseText
                banAlert.classList.remove("hidden")
            })
        }

        $("#banModal").on('hidden.bs.modal', () => banAlert.classList.add("hidden"))


    </script>

{% endblock %}

app/logviewer/templates/logviewer/index.html
{% extends 'party/base.html' %}

{% block content %}
    <div class="container">
        <h3>Select logfile to view</h3>

        <table class="table table-responsive">
            <tbody>
            {% for file in files %}
                <tr>
                    <td><a href="{% url "logviewer:detail" file.0 %}">{{ file.0 }}</a></td>
                    <td>{{ file.1|filesizeformat }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>

{% endblock %}