app/config/urls.py
import sys
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from rest_framework import routers

from authentication.api.v1.views import MeView
from party.api.v1.routers import router as v1_party_router
from authentication.api.v1.routers import router as v1_authentication_router
from party.views.feeds import FeedsView
from common.feeds import PartyFeedRss2, PartyFeedRss09, PartyFeedAtom1

v1router = routers.DefaultRouter() if settings.DEBUG else routers.SimpleRouter()

v1router.registry.extend(v1_party_router.registry)
if settings.DEBUG:
    v1router.registry.extend(v1_authentication_router.registry)

urlpatterns = [
    path('autocomplete/', include('autocomplete_contrib.urls')),
    path('admin/', admin.site.urls),
    path('feeds/', FeedsView.as_view(), name="feeds"),
    path('feeds/parties_rss2.xml', PartyFeedRss2(), name="feeds-rss2"),
    path('feeds/parties_rss09.xml', PartyFeedRss09(), name="feeds-rss09"),
    path('feeds/parties_atom1.xml', PartyFeedAtom1(), name="feeds-atom1"),
    path('api/v1/', include(v1router.urls)),
    path('api/v1/me/', MeView.as_view(), name='me'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('logviewer/', include('logviewer.urls')),
    path('account/', include('authentication.urls')),
    path('', include('party.urls')),
]

if settings.DEBUG and "test" not in sys.argv:
    import debug_toolbar

    # This will enable static assets even when debugging using gunicorn etc
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

app/party/urls.py
from django.urls import path

from party.views.site import LandingPageView, AboutView, SearchView, StatsView, ShareView, health_check
from party.views.party import PartyListView, PartyCreateView, PartyDetailView, PartyUpdateView, DemopartyNetCreateView
from party.views.trip import TripToCreateView, TripFromCreateView, TripToUpdateView, TripFromUpdateView, \
    TripToCloneView, TripFromCloneView, TripDeleteView

app_name = "party"

urlpatterns = [
    path('', LandingPageView.as_view(), name="landing_page"),
    path('about/', AboutView.as_view(), name="about"),
    path('search/', SearchView.as_view(), name="search"),
    path('stats/', StatsView.as_view(), name="stats"),
    path('health-check/', health_check, name="health-check"),
    path('shared/<str:short_uuid>/', ShareView.as_view(), name="shared"),
    path('list/', PartyListView.as_view(), name="list"),
    path('list/<int:year>/', PartyListView.as_view(), name="list-by-year"),
    path('list/<str:country>/', PartyListView.as_view(), name="list-by-country"),
    path('list/<str:country>/<int:year>/', PartyListView.as_view(), name="list-by-country-and-year"),
    path('create/', PartyCreateView.as_view(), name="create"),
    path('create/demopartynet/', DemopartyNetCreateView.as_view(), name="demopartynet-create"),
    path('<slug:slug>/update/', PartyUpdateView.as_view(), name="update"),
    path('create-trip-to/<slug:slug>/', TripToCreateView.as_view(), name="create-trip-to"),
    path('create-trip-from/<slug:slug>/', TripFromCreateView.as_view(), name="create-trip-from"),
    path('clone-trip-to/<slug:slug>/from_trip/<int:trip>/', TripToCloneView.as_view(), name="clone-trip-to"),
    path('clone-trip-from/<slug:slug>/from_trip/<int:trip>/', TripFromCloneView.as_view(), name="clone-trip-from"),
    path('update-trip-to/<slug:slug>/<int:trip>/', TripToUpdateView.as_view(), name="update-trip-to"),
    path('update-trip-from/<slug:slug>/<int:trip>/', TripFromUpdateView.as_view(), name="update-trip-from"),
    path('<slug:slug>/delete-trip/<int:pk>/', TripDeleteView.as_view(), name="delete-trip"),
    path('<slug:slug>/', PartyDetailView.as_view(), name="detail")
]

app/party/views/feeds.py
from django.views.generic import TemplateView


class FeedsView(TemplateView):
    template_name = 'party/feeds.html'

app/party/views/party.py
import string

import requests
from django.db.models.functions import Lower
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.text import slugify
from django.views import generic
from django_countries import countries

from common.mixins import LoginRequiredMixin
from party.forms import PartyForm, PartyFormNative
from party.models import Party
from party.parsers import get_country, get_location, get_start_date, get_end_date


class PartyListView(generic.ListView):
    template_name = 'party/party_list.html'
    model = Party

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ret_arr = []
        for i in ["country", "year"]:
            if self.kwargs.get(i):
                ret_arr.append(string.capwords(str(self.kwargs.get(i))))
        ctx["breadcrumb"] = ret_arr
        ctx["party_years"] = list(Party.objects.filter(visible=True).values_list("date_start__year", flat=True).order_by("date_start__year").distinct())
        party_countries = [countries.name(x.get("country")) for x in Party.objects.filter(visible=True).values("country").distinct()]
        ctx["party_countries"] = sorted(party_countries)
        return ctx

    def get_queryset(self):
        qs = Party.objects.filter(visible=True).order_by(Lower("name"), "date_start")
        if "year" in self.kwargs:
            qs = qs.filter(date_start__year=self.kwargs.get("year"))
        if "country" in self.kwargs:
            qs = qs.filter(country__icontains=self.kwargs.get("country"))
        return qs


class PartyCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'party/party_create.html'
    model = Party
    queryset = Party.objects.filter(visible=True)

    def get_form_class(self):
        if self.request.user_agent.is_mobile:
            return PartyFormNative
        return PartyForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.visible = True
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("party:landing_page")


class PartyUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'party/party_create.html'
    model = Party
    form_class = PartyForm

    def get(self, request, *args, **kwargs):
        party = self.get_object()
        if party.has_ended:
            messages.warning(request, "Cannot modify a party that has ended")
            return redirect(reverse("party:landing_page"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        form.instance.visible = self.get_object().visible
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("party:detail", kwargs=self.kwargs)


class PartyDetailView(generic.DetailView):
    template_name = 'party/party_detail.html'
    model = Party

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        trips = self.object.trips.select_related("created_by").order_by(Lower("display_name"))
        ctx["inbound"] = trips.filter(towards_party=True)
        ctx["outbound"] = trips.filter(towards_party=False)
        return ctx


class DemopartyNetCreateView(LoginRequiredMixin, generic.RedirectView):
    def get(self, request, *args, **kwargs):
        demopartynet_url = request.GET.get("url", None)
        if not demopartynet_url:
            messages.warning(request, "No demoparty.net url provided")
            return redirect(reverse("party:landing_page"))

        res = requests.get(timeout=10, url=f"https://www.demoparty.net{demopartynet_url}.jsonld")
        if res.status_code != 200:
            messages.warning(request, "Error fetching data from demoparty.net")
            return redirect(reverse("party:landing_page"))

        j = res.json()

        defaults = {
            "created_by": request.user,
            "location": get_location(j),
            "country": get_country(j),
            "name": j.get("name"),
            "www": j.get("url"),
            "date_start": get_start_date(j),
            "date_end": get_end_date(j),
        }

        party, _ = Party.objects.update_or_create(slug=slugify(defaults["name"]), defaults=defaults)
        return redirect('party:detail', party.slug)

app/party/views/site.py
import sys
import sqlite3
import rest_framework

from django import VERSION as DJANGO_VERSION
from django.contrib import messages
from django.db.models import Q, Count, F, When, Value, Case
from django.db.models.functions import Lower
from django.db import connections
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.views import generic
from django_countries import countries

from authentication.models import Share
from party.models import Party, Trip
from common.parsers import get_dependency_version


def health_check(request):
    db_ok = all(conn.cursor().execute("SELECT 1") for conn in connections.all())
    status_code = 200 if db_ok else 503
    return HttpResponse(status=status_code)


class LandingPageView(generic.TemplateView):
    template_name = 'party/landing_page.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['upcoming_parties'] = (Party.upcoming_parties
                                   .filter(visible=True)
                                   .annotate(towards_party_count=Count("trips",
                                                                       filter=Q(trips__towards_party=True)),
                                             towards_home_count=Count("trips",
                                                                      filter=Q(trips__towards_party=False))
                                             )
                                   )
        ctx['past_parties'] = Party.past_parties.filter(visible=True)
        return ctx


class AboutView(generic.TemplateView):
    template_name = 'party/about.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        ctx["django_version"] = '.'.join(map(str, list(DJANGO_VERSION[0:3])))
        ctx["rest_framework_version"] = rest_framework.VERSION
        ctx["python_version"] = sys.version.split(" ")[0]
        ctx["sqlite_version"] = sqlite3.version
        ctx["bootstrap_version"] = get_dependency_version("bootstrap")
        ctx["fontawesome_version"] = get_dependency_version("font-awesome")
        ctx["jquery_version"] = get_dependency_version("jquery")
        return ctx


class SearchView(generic.TemplateView):
    template_name = 'party/search.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        query = self.request.GET.get("search", None)

        if query and self.request.user.is_authenticated:
            filters = Q()
            for item in query.split():
                item = item.strip()
                if item.isdigit() and int(item) >= 2012:
                    filters &= Q(date_start__year=item)
                else:
                    filters &= (
                            Q(name__icontains=item) |
                            Q(trips__display_name__icontains=item) |
                            Q(country__icontains=item) |
                            Q(location__icontains=item)
                    )

            ctx["results"] = (Party.objects.filter(filters, visible=True).order_by("date_start__year", Lower("name")).distinct())
        ctx["query"] = query
        return ctx


class StatsView(generic.TemplateView):
    template_name = 'party/stats.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, level=messages.WARNING, message="You need to be logged in to view stats")
            return redirect("party:landing_page")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        whens = [When(country_code=k, then=Value(v)) for k, v in dict(countries).items()]
        ctx["parties"] = Party.objects \
                             .filter(trips__towards_party=True, visible=True) \
                             .distinct() \
                             .annotate(Count("trips")) \
                             .order_by("-trips__count")[:10]
        ctx["display_names"] = Trip.objects \
                                   .filter(towards_party=True) \
                                   .values("display_name") \
                                   .annotate(count=Count("display_name")) \
                                   .order_by("-count")[:10]
        ctx["countries"] = list(Party.objects.filter(visible=True).exclude(country__name="None")
                                .annotate(country_code=F("country"))
                                .annotate(country_name=Case(*whens))
                                .values("country_code", "country_name")
                                .annotate(count=Count(F("country_code")))
                                .order_by("-count"))

        ctx["countries_piechart"] = [
            [x.get("country_name") for x in ctx["countries"]],
            [x.get("count") for x in ctx["countries"]]
        ]

        ctx["transportation"] = list(Trip.objects
                                     .values("type")
                                     .annotate(count=Count("type"))
                                     .order_by("-count"))

        ctx["transportation_piechart"] = [
            [x.get("type").capitalize() for x in ctx["transportation"]],
            [x.get("count") for x in ctx["transportation"]]
        ]

        ctx["towns"] = Trip.objects \
                           .filter(towards_party=True) \
                           .values("departure_town") \
                           .annotate(count=Count("departure_town")) \
                           .order_by("-count")[:10]
        ctx["airlines"] = Trip.objects \
                              .filter(type=Trip.PLANE, detail1__iregex=r"\S\S.+") \
                              .values("detail1") \
                              .annotate(count=(Count(Lower("detail1")))) \
                              .order_by("-count")[:10]
        ctx["trips_per_year"] = Trip.objects \
                                    .filter(towards_party=True) \
                                    .values("departure_datetime__year") \
                                    .annotate(count=Count("departure_datetime__year")) \
                                    .order_by("-count")[:10]
        ctx["trips_per_country"] = Trip.objects \
                                       .filter(towards_party=True) \
                                       .values("departure_country") \
                                       .annotate(count=Count("departure_country")) \
                                       .order_by("-count")[:10]
        return ctx


class ShareView(generic.TemplateView):
    template_name = "party/shared.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        try:
            ctx["share"] = Share.objects.select_related("user").get(short_uuid=self.kwargs.get("short_uuid"))
        except Share.DoesNotExist:
            raise Http404
        ctx["user_parties"] = (Party.objects
                               .filter(trips__in=ctx["share"].user.trips.all())
                               .order_by("name", "date_start").distinct())
        return ctx

app/party/templates/snippets/cf_flag.html
<div style="width: 20px; display: inline-block">
    {% if not country %}
        <i class="far fa-question-circle"></i>
    {% else %}
        <a href="{% url "party:list-by-country" country.name %}" class="text-decoration-none">
        <img src="/static/flags/{{ country.code|lower }}.gif"
             height="10" title="{{ country.name }}"
             alt="{{ country.name }}"
             onerror="this.style.display='none'">
        </a>
    {% endif %}
</div>

app/party/templates/snippets/flag.html
<div class="text-center" style="width: 20px; display: inline-block">
    {% if not country %}
        <i class="far fa-question-circle"></i>
    {% else %}
        {% if not hide_url %}
            <a href="{% url "party:list-by-country" country.name %}" class="text-decoration-none">
        {% endif %}
    <span class="fi fi-{{ country.code|lower }}" title="{{ country.name }}" style="height: 12px;"></span>
    {% if not hide_url %}
        </a>
    {% endif %}
    {% endif %}
</div>

app/party/templates/snippets/user-party-table.html
<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active fw-bold" data-bs-toggle="tab" href="#by_name" role="tab">
            By Name</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link fw-bold" data-bs-toggle="tab" href="#by_year" role="tab">
            By Year</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link fw-bold" data-bs-toggle="tab" href="#by_country" role="tab">
            By Country</a>
    </li>
</ul>
<div class="tab-content mt-2">
    <div class="tab-pane active show" id="by_name" role="tabpanel">
        {% regroup user_parties by name as parties %}
        <ul class="list-group list-group-flush">
            {% for party in parties %}
                <li class="list-group-item p-1">
                                    <span class="pe-1">
                                        {{ party.grouper }}
                                    </span>
                    {% for party_instance in party.list %}
                        <a class="pe-1" href="{% url 'party:detail' party_instance.slug %}">
                            {{ party_instance.date_start.year }}
                        </a>
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="tab-pane" id="by_year" role="tabpanel">
        {% regroup user_parties|dictsort:"date_start.year" by date_start.year as parties %}
        <ul class="list-group list-group-flush">
            {% for party in parties %}
                <li class="list-group-item p-1">
                                    <span class="pe-1">
                                        {{ party.grouper }}
                                    </span>
                    {% for party_instance in party.list %}
                        <a class="pe-1" href="{% url 'party:detail' party_instance.slug %}">
                            {{ party_instance.name }}
                        </a>
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="tab-pane" id="by_country" role="tabpanel">
        {% regroup user_parties|dictsort:"country.name" by country as parties %}
        <ul class="list-group list-group-flush">
            {% for party in parties %}
                <li class="list-group-item p-1">
                                    <span class="pe-1">
                                        {% include 'snippets/flag.html' with country=party.grouper %}
                                        {{ party.grouper.name }}
                                    </span>
                    {% for party_instance in party.list %}
                        <a class="pe-1" href="{% url 'party:detail' party_instance.slug %}">
                            {{ party_instance.name }}
                            <small>({{ party_instance.date_start.year }})</small>
                        </a>
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<hr class="w-25"/>
<p>Total parties: {{ user_parties.count }}</p>